fastlane_version '2.197.0'

platform :ios do
    desc 'Build the iOS application.'
    lane :build do
        build_app(
            scheme: "RIDEN",
            workspace: 'ios/RIDEN.xcworkspace',
            include_bitcode: true,
            output_directory: 'build',
            codesigning_identity: 'Apple Distribution: Tom Sacher (W4DRGXG6V5)',
            clean: false,
            export_method: 'ad-hoc',
            export_options: 'export-options.plist'
        )
    end

    desc 'Build the iOS application (CI Edition).'
    lane :ci do
        build()
    end

    desc 'Ship to Testflight.'
    lane :beta do
        api_key = app_store_connect_api_key(
            key_id: "AVKPS4JC36",
            issuer_id: "aeca5e70-59b6-416f-b244-c433e3fad717",
            key_filepath: "./APPSTORE_KEY.p8",
            duration: 1200
        )
        pilot
    end
end
