fastlane_version '2.197.0'

before_all do
  ensure_git_branch(branch: 'ci/fastlane')
  ensure_git_status_clean
end

platform :ios do
   desc 'Build the iOS application.'
   lane :build do
      update_code_signing_settings(
       use_automatic_signing: true,
       path: "ios/RIDEN.xcworkspace")
      build_app(scheme: "RIDEN PROD",
        workspace: 'ios/RIDEN.xcworkspace',
        include_bitcode: true)
   end

   desc 'Ship to Testflight.'
     lane :beta do
       api_key = app_store_connect_api_key(
         key_id: "AVKPS4JC36",
         issuer_id: "aeca5e70-59b6-416f-b244-c433e3fad717",
         key_filepath: "./APPSTORE_KEY.p8",
         duration: 1200
       )
       pilot
     end
end
