fastlane_version '2.197.0'

platform :ios do
    desc 'Build the iOS application.'
    lane :build do
        build_app(
            scheme: "RIDEN",
            workspace: 'ios/RIDEN.xcworkspace',
            include_bitcode: true,
            output_directory: 'build',
            codesigning_identity: 'Apple Distribution: Tom Sacher (W4DRGXG6V5)',
            clean: false,
            export_method: 'ad-hoc',
            export_options: 'export-options.plist'
        )
    end

    desc 'Build the iOS application (CI Edition).'
    lane :ci do
        create_keychain(
            name: "RIDEN",
            path: ENV["HOME"] + "/Library/Keychains/RIDEN-db",
            default_keychain: false,
            unlock: true,
            timeout: 3600,
            add_to_search_list: true,
            lock_when_sleeps: true
        )
        import_certificate(
            certificate_path: "./certificates/Certificates/Distribution_Certificate.p12",
            keychain_path: ENV["HOME"] + "/Library/Keychains/RIDEN-db",
            log_output: true
        )
        install_provisioning_profile(path: "./certificates/Provisioning_Profiles/Riden_Ad_Hoc.mobileprovision")
        build()
    end

    desc 'Build the iOS application (CI Edition).'
    lane :ci_cleanup do
        delete_keychain(keychain_path: ENV["HOME"] + "/Library/Keychains/RIDEN-db")
    end

    desc 'Ship to Testflight.'
    lane :beta do
        api_key = app_store_connect_api_key(
            key_id: "AVKPS4JC36",
            issuer_id: "aeca5e70-59b6-416f-b244-c433e3fad717",
            key_filepath: "./APPSTORE_KEY.p8",
            duration: 1200
        )
        pilot
    end
end
