name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pr:
    name: Semantic PR
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          subjectPattern: ^(?![A-Z]).+$
