name: Publish Canary Release

on:
  push:
    branches:
      - ci/fastlane

jobs:
  build:
    name: Build iOS Release
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing Dependencies
        run: |
            yarn install --frozen-lockfile
            bundle update
      - name: Running Type Check
        run: yarn tsc --noEmit
      - name: Building ipa
        run: yarn ios:build
      - name: Archiving built ipa
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: RIDEN.ipa
      - name: Preparing APPSTORE_KEY.p8
        run: echo ${{ secrets.APPSTORE_CONNECT_KEY }} | base64 -d > APPSTORE_KEY.p8
      - name: Pushing ipa to AppStore Connect
        run: yarn ios:beta
