name: Publish Canary Release

on:
  push:
    branches:
      - ci/fastlane

jobs:
  build:
    name: Build iOS Release
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: CocoaPods Cache
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Prepare yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installing Dependencies
        run: |
            yarn install --frozen-lockfile
            bundle install
      - name: Running Type Check
        run: yarn tsc --noEmit
      - name: Starting Metro in Background
        run: yarn start &
      - name: Check if Metro is running
        run: curl localhost:8081
      - name: Building ipa
        run: yarn ios:build
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.HIGH5_BASIC_AUTH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Archiving built ipa
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: RIDEN.ipa
      - name: Preparing APPSTORE_KEY.p8
        run: echo ${{ secrets.APPSTORE_CONNECT_KEY }} | base64 -d > APPSTORE_KEY.p8
      - name: Pushing ipa to AppStore Connect
        run: yarn ios:beta
      - name: Killing Metro
        run: killall -9 node
